[package]
name = "rust-sandbox"
version = "0.1.0"
license = "MIT"
authors = ["8bit-euclid <8bit-euclid@gmail.com>"]
repository = "https://github.com/8bit-euclid/rust-sandbox"
edition = "2021"

[dependencies]
rand = "0.9.2"